/**
 * Canonical default categorization rules (P3-04).
 *
 * Single source of truth for the seeded rule set: it drives the i18n keys
 * (`rules.defaults.<key>`), the tests, and mirrors exactly what
 * `public.seed_default_rules()` inserts in migration `0008`. If you change this
 * list, update the SQL seed and the message catalogs to match (tests assert
 * referential integrity against the default categories, valid conditions,
 * unique keys/priorities, and EN/ES label parity).
 *
 * Each rule is a single `description contains <token>` clause (the matcher is
 * case-insensitive); OR across merchants for one category is expressed as
 * multiple rules (the AND-only model). Priorities are explicit and distinct so
 * precedence is deterministic and a specific token outranks a generic one
 * (`uber eats` before `uber`). All defaults sit at priority ≥ 100 so any
 * user-authored rule (default priority 0) wins.
 */

export interface DefaultRule {
  /** Target category's `name_key` (must be in DEFAULT_CATEGORY_KEYS). */
  categoryKey: string
  /** Description substring to match (compared case-insensitively). */
  contains: string
  /** Literal `name` fallback persisted alongside `name_key`. */
  en: string
  /** Stable `name_key` on the row + i18n key (`rules.defaults.<key>`). */
  key: string
  /** Explicit, distinct; lower = higher precedence. */
  priority: number
}

export const DEFAULT_RULES: readonly DefaultRule[] = [
  // — Groceries (food → groceries) —
  {
    key: 'mercadona',
    en: 'Mercadona',
    categoryKey: 'groceries',
    contains: 'mercadona',
    priority: 100,
  },
  {
    key: 'carrefour',
    en: 'Carrefour',
    categoryKey: 'groceries',
    contains: 'carrefour',
    priority: 101,
  },
  {
    key: 'lidl',
    en: 'Lidl',
    categoryKey: 'groceries',
    contains: 'lidl',
    priority: 102,
  },
  {
    key: 'dia',
    en: 'Dia',
    categoryKey: 'groceries',
    contains: 'supermercado dia',
    priority: 103,
  },
  {
    key: 'aldi',
    en: 'Aldi',
    categoryKey: 'groceries',
    contains: 'aldi',
    priority: 104,
  },
  {
    key: 'consum',
    en: 'Consum',
    categoryKey: 'groceries',
    contains: 'consum',
    priority: 105,
  },
  {
    key: 'eroski',
    en: 'Eroski',
    categoryKey: 'groceries',
    contains: 'eroski',
    priority: 106,
  },
  // — Restaurants & food delivery (food → restaurants) — listed before `uber` —
  {
    key: 'glovo',
    en: 'Glovo',
    categoryKey: 'restaurants',
    contains: 'glovo',
    priority: 110,
  },
  {
    key: 'uber_eats',
    en: 'Uber Eats',
    categoryKey: 'restaurants',
    contains: 'uber eats',
    priority: 111,
  },
  {
    key: 'just_eat',
    en: 'Just Eat',
    categoryKey: 'restaurants',
    contains: 'just eat',
    priority: 112,
  },
  {
    key: 'deliveroo',
    en: 'Deliveroo',
    categoryKey: 'restaurants',
    contains: 'deliveroo',
    priority: 113,
  },
  {
    key: 'mcdonalds',
    en: "McDonald's",
    categoryKey: 'restaurants',
    contains: 'mcdonald',
    priority: 114,
  },
  {
    key: 'starbucks',
    en: 'Starbucks',
    categoryKey: 'restaurants',
    contains: 'starbucks',
    priority: 115,
  },
  {
    key: 'telepizza',
    en: 'Telepizza',
    categoryKey: 'restaurants',
    contains: 'telepizza',
    priority: 116,
  },
  // — Transport — `uber` after `uber eats` so delivery isn't miscounted —
  {
    key: 'uber',
    en: 'Uber',
    categoryKey: 'transport',
    contains: 'uber',
    priority: 120,
  },
  {
    key: 'cabify',
    en: 'Cabify',
    categoryKey: 'transport',
    contains: 'cabify',
    priority: 121,
  },
  {
    key: 'renfe',
    en: 'Renfe',
    categoryKey: 'transport',
    contains: 'renfe',
    priority: 122,
  },
  {
    key: 'repsol',
    en: 'Repsol',
    categoryKey: 'transport',
    contains: 'repsol',
    priority: 123,
  },
  {
    key: 'cepsa',
    en: 'Cepsa',
    categoryKey: 'transport',
    contains: 'cepsa',
    priority: 124,
  },
  // — Utilities & telecom —
  {
    key: 'endesa',
    en: 'Endesa',
    categoryKey: 'utilities',
    contains: 'endesa',
    priority: 130,
  },
  {
    key: 'iberdrola',
    en: 'Iberdrola',
    categoryKey: 'utilities',
    contains: 'iberdrola',
    priority: 131,
  },
  {
    key: 'naturgy',
    en: 'Naturgy',
    categoryKey: 'utilities',
    contains: 'naturgy',
    priority: 132,
  },
  {
    key: 'movistar',
    en: 'Movistar',
    categoryKey: 'utilities',
    contains: 'movistar',
    priority: 133,
  },
  {
    key: 'vodafone',
    en: 'Vodafone',
    categoryKey: 'utilities',
    contains: 'vodafone',
    priority: 134,
  },
  {
    key: 'orange',
    en: 'Orange',
    categoryKey: 'utilities',
    contains: 'orange',
    priority: 135,
  },
  // — Income (salary) —
  {
    key: 'nomina',
    en: 'Payroll (Nómina)',
    categoryKey: 'salary',
    contains: 'nomina',
    priority: 140,
  },
  {
    key: 'payroll',
    en: 'Payroll',
    categoryKey: 'salary',
    contains: 'payroll',
    priority: 141,
  },
  // — Groceries, more supermarkets (food → groceries) —
  {
    key: 'alcampo',
    en: 'Alcampo',
    categoryKey: 'groceries',
    contains: 'alcampo',
    priority: 150,
  },
  {
    key: 'hipercor',
    en: 'Hipercor',
    categoryKey: 'groceries',
    contains: 'hipercor',
    priority: 151,
  },
  {
    key: 'condis',
    en: 'Condis',
    categoryKey: 'groceries',
    contains: 'condis',
    priority: 152,
  },
  {
    key: 'bonpreu',
    en: 'Bonpreu',
    categoryKey: 'groceries',
    contains: 'bonpreu',
    priority: 153,
  },
  {
    key: 'walmart',
    en: 'Walmart',
    categoryKey: 'groceries',
    contains: 'walmart',
    priority: 154,
  },
  {
    key: 'tesco',
    en: 'Tesco',
    categoryKey: 'groceries',
    contains: 'tesco',
    priority: 155,
  },
  {
    key: 'supermercado',
    en: 'Supermarket',
    categoryKey: 'groceries',
    contains: 'supermercado',
    priority: 156,
  },
  {
    key: 'fruteria',
    en: 'Greengrocer',
    categoryKey: 'groceries',
    contains: 'fruteria',
    priority: 157,
  },
  {
    key: 'panaderia',
    en: 'Bakery',
    categoryKey: 'groceries',
    contains: 'panaderia',
    priority: 158,
  },
  // — Restaurants & delivery, more merchants (food → restaurants) —
  {
    key: 'burger_king',
    en: 'Burger King',
    categoryKey: 'restaurants',
    contains: 'burger king',
    priority: 160,
  },
  {
    key: 'kfc',
    en: 'KFC',
    categoryKey: 'restaurants',
    contains: 'kfc',
    priority: 161,
  },
  {
    key: 'dominos',
    en: "Domino's",
    categoryKey: 'restaurants',
    contains: 'domino',
    priority: 162,
  },
  {
    key: 'pizza_hut',
    en: 'Pizza Hut',
    categoryKey: 'restaurants',
    contains: 'pizza hut',
    priority: 163,
  },
  {
    key: 'taco_bell',
    en: 'Taco Bell',
    categoryKey: 'restaurants',
    contains: 'taco bell',
    priority: 164,
  },
  {
    key: 'doordash',
    en: 'DoorDash',
    categoryKey: 'restaurants',
    contains: 'doordash',
    priority: 165,
  },
  {
    key: 'costa_coffee',
    en: 'Costa Coffee',
    categoryKey: 'restaurants',
    contains: 'costa coffee',
    priority: 166,
  },
  {
    key: 'dunkin',
    en: 'Dunkin',
    categoryKey: 'restaurants',
    contains: 'dunkin',
    priority: 167,
  },
  {
    key: 'restaurante',
    en: 'Restaurant',
    categoryKey: 'restaurants',
    contains: 'restaurante',
    priority: 168,
  },
  {
    key: 'cafeteria',
    en: 'Café',
    categoryKey: 'restaurants',
    contains: 'cafeteria',
    priority: 169,
  },
  {
    key: 'pizzeria',
    en: 'Pizzeria',
    categoryKey: 'restaurants',
    contains: 'pizzeria',
    priority: 170,
  },
  {
    key: 'sushi',
    en: 'Sushi',
    categoryKey: 'restaurants',
    contains: 'sushi',
    priority: 171,
  },
  {
    key: 'hamburgueseria',
    en: 'Burger joint',
    categoryKey: 'restaurants',
    contains: 'hamburgueseria',
    priority: 172,
  },
  {
    key: 'cerveceria',
    en: 'Beer hall',
    categoryKey: 'restaurants',
    contains: 'cerveceria',
    priority: 173,
  },
  // — Transport, fuel/parking/public transport/rideshare —
  {
    key: 'shell',
    en: 'Shell',
    categoryKey: 'transport',
    contains: 'shell',
    priority: 180,
  },
  {
    key: 'galp',
    en: 'Galp',
    categoryKey: 'transport',
    contains: 'galp',
    priority: 181,
  },
  {
    key: 'gasolinera',
    en: 'Gas station',
    categoryKey: 'transport',
    contains: 'gasolinera',
    priority: 182,
  },
  {
    key: 'parking',
    en: 'Parking',
    categoryKey: 'transport',
    contains: 'parking',
    priority: 183,
  },
  {
    key: 'aparcamiento',
    en: 'Car park',
    categoryKey: 'transport',
    contains: 'aparcamiento',
    priority: 184,
  },
  {
    key: 'peaje',
    en: 'Toll (peaje)',
    categoryKey: 'transport',
    contains: 'peaje',
    priority: 185,
  },
  {
    key: 'metro',
    en: 'Metro',
    categoryKey: 'transport',
    contains: 'metro ',
    priority: 186,
  },
  {
    key: 'autobus',
    en: 'Bus',
    categoryKey: 'transport',
    contains: 'autobus',
    priority: 187,
  },
  {
    key: 'cercanias',
    en: 'Cercanías',
    categoryKey: 'transport',
    contains: 'cercanias',
    priority: 188,
  },
  {
    key: 'bicing',
    en: 'Bicing',
    categoryKey: 'transport',
    contains: 'bicing',
    priority: 189,
  },
  {
    key: 'taxi',
    en: 'Taxi',
    categoryKey: 'transport',
    contains: 'taxi',
    priority: 190,
  },
  {
    key: 'freenow',
    en: 'Free Now',
    categoryKey: 'transport',
    contains: 'freenow',
    priority: 191,
  },
  {
    key: 'blablacar',
    en: 'BlaBlaCar',
    categoryKey: 'transport',
    contains: 'blablacar',
    priority: 192,
  },
  // — Utilities & telecom, more providers —
  {
    key: 'holaluz',
    en: 'Holaluz',
    categoryKey: 'utilities',
    contains: 'holaluz',
    priority: 200,
  },
  {
    key: 'jazztel',
    en: 'Jazztel',
    categoryKey: 'utilities',
    contains: 'jazztel',
    priority: 201,
  },
  {
    key: 'masmovil',
    en: 'MásMóvil',
    categoryKey: 'utilities',
    contains: 'masmovil',
    priority: 202,
  },
  {
    key: 'yoigo',
    en: 'Yoigo',
    categoryKey: 'utilities',
    contains: 'yoigo',
    priority: 203,
  },
  {
    key: 'digi',
    en: 'Digi',
    categoryKey: 'utilities',
    contains: 'digi',
    priority: 204,
  },
  {
    key: 'electricidad',
    en: 'Electricity',
    categoryKey: 'utilities',
    contains: 'electricidad',
    priority: 205,
  },
  {
    key: 'internet',
    en: 'Internet',
    categoryKey: 'utilities',
    contains: 'internet',
    priority: 206,
  },
  {
    key: 'telefonia',
    en: 'Telecom',
    categoryKey: 'utilities',
    contains: 'telefonia',
    priority: 207,
  },
  {
    key: 'canal_de_isabel',
    en: 'Canal de Isabel II',
    categoryKey: 'utilities',
    contains: 'canal de isabel',
    priority: 208,
  },
  // — Health: pharmacy, medical, insurance, gym —
  {
    key: 'farmacia',
    en: 'Pharmacy',
    categoryKey: 'health',
    contains: 'farmacia',
    priority: 220,
  },
  {
    key: 'pharmacy',
    en: 'Pharmacy',
    categoryKey: 'health',
    contains: 'pharmacy',
    priority: 221,
  },
  {
    key: 'sanitas',
    en: 'Sanitas',
    categoryKey: 'health',
    contains: 'sanitas',
    priority: 222,
  },
  {
    key: 'adeslas',
    en: 'Adeslas',
    categoryKey: 'health',
    contains: 'adeslas',
    priority: 223,
  },
  {
    key: 'asisa',
    en: 'Asisa',
    categoryKey: 'health',
    contains: 'asisa',
    priority: 224,
  },
  {
    key: 'dkv',
    en: 'DKV',
    categoryKey: 'health',
    contains: 'dkv',
    priority: 225,
  },
  {
    key: 'gimnasio',
    en: 'Gym',
    categoryKey: 'health',
    contains: 'gimnasio',
    priority: 226,
  },
  {
    key: 'fisioterapia',
    en: 'Physiotherapy',
    categoryKey: 'health',
    contains: 'fisioterapia',
    priority: 227,
  },
  {
    key: 'dentista',
    en: 'Dentist',
    categoryKey: 'health',
    contains: 'dentista',
    priority: 228,
  },
  {
    key: 'clinica',
    en: 'Clinic',
    categoryKey: 'health',
    contains: 'clinica',
    priority: 229,
  },
  {
    key: 'hospital',
    en: 'Hospital',
    categoryKey: 'health',
    contains: 'hospital',
    priority: 230,
  },
  // — Shopping: clothing, electronics, home, general —
  {
    key: 'zara',
    en: 'Zara',
    categoryKey: 'shopping',
    contains: 'zara',
    priority: 240,
  },
  {
    key: 'hym',
    en: 'H&M',
    categoryKey: 'shopping',
    contains: 'h&m',
    priority: 241,
  },
  {
    key: 'primark',
    en: 'Primark',
    categoryKey: 'shopping',
    contains: 'primark',
    priority: 242,
  },
  {
    key: 'zalando',
    en: 'Zalando',
    categoryKey: 'shopping',
    contains: 'zalando',
    priority: 243,
  },
  {
    key: 'ikea',
    en: 'IKEA',
    categoryKey: 'shopping',
    contains: 'ikea',
    priority: 244,
  },
  {
    key: 'leroy_merlin',
    en: 'Leroy Merlin',
    categoryKey: 'shopping',
    contains: 'leroy merlin',
    priority: 245,
  },
  {
    key: 'mediamarkt',
    en: 'MediaMarkt',
    categoryKey: 'shopping',
    contains: 'mediamarkt',
    priority: 246,
  },
  {
    key: 'fnac',
    en: 'Fnac',
    categoryKey: 'shopping',
    contains: 'fnac',
    priority: 247,
  },
  {
    key: 'amazon',
    en: 'Amazon',
    categoryKey: 'shopping',
    contains: 'amazon',
    priority: 248,
  },
  {
    key: 'el_corte_ingles',
    en: 'El Corte Inglés',
    categoryKey: 'shopping',
    contains: 'el corte ingles',
    priority: 249,
  },
  {
    key: 'aliexpress',
    en: 'AliExpress',
    categoryKey: 'shopping',
    contains: 'aliexpress',
    priority: 250,
  },
  {
    key: 'decathlon',
    en: 'Decathlon',
    categoryKey: 'shopping',
    contains: 'decathlon',
    priority: 251,
  },
  // — Entertainment: streaming, gaming, leisure —
  {
    key: 'netflix',
    en: 'Netflix',
    categoryKey: 'entertainment',
    contains: 'netflix',
    priority: 260,
  },
  {
    key: 'spotify',
    en: 'Spotify',
    categoryKey: 'entertainment',
    contains: 'spotify',
    priority: 261,
  },
  {
    key: 'hbo_max',
    en: 'HBO Max',
    categoryKey: 'entertainment',
    contains: 'hbo max',
    priority: 262,
  },
  {
    key: 'disney_plus',
    en: 'Disney+',
    categoryKey: 'entertainment',
    contains: 'disney+',
    priority: 263,
  },
  {
    key: 'dazn',
    en: 'DAZN',
    categoryKey: 'entertainment',
    contains: 'dazn',
    priority: 264,
  },
  {
    key: 'playstation',
    en: 'PlayStation',
    categoryKey: 'entertainment',
    contains: 'playstation',
    priority: 265,
  },
  {
    key: 'xbox',
    en: 'Xbox',
    categoryKey: 'entertainment',
    contains: 'xbox',
    priority: 266,
  },
  {
    key: 'nintendo',
    en: 'Nintendo',
    categoryKey: 'entertainment',
    contains: 'nintendo',
    priority: 267,
  },
  {
    key: 'cine',
    en: 'Cinema',
    categoryKey: 'entertainment',
    contains: 'cine ',
    priority: 268,
  },
  {
    key: 'teatro',
    en: 'Theatre',
    categoryKey: 'entertainment',
    contains: 'teatro',
    priority: 269,
  },
  {
    key: 'ticketmaster',
    en: 'Ticketmaster',
    categoryKey: 'entertainment',
    contains: 'ticketmaster',
    priority: 270,
  },
  {
    key: 'filmin',
    en: 'Filmin',
    categoryKey: 'entertainment',
    contains: 'filmin',
    priority: 271,
  },
  // — Education —
  {
    key: 'udemy',
    en: 'Udemy',
    categoryKey: 'education',
    contains: 'udemy',
    priority: 280,
  },
  {
    key: 'coursera',
    en: 'Coursera',
    categoryKey: 'education',
    contains: 'coursera',
    priority: 281,
  },
  {
    key: 'duolingo',
    en: 'Duolingo',
    categoryKey: 'education',
    contains: 'duolingo',
    priority: 282,
  },
  {
    key: 'universidad',
    en: 'University',
    categoryKey: 'education',
    contains: 'universidad',
    priority: 283,
  },
  {
    key: 'matricula',
    en: 'Tuition (matrícula)',
    categoryKey: 'education',
    contains: 'matricula',
    priority: 284,
  },
  {
    key: 'masterclass',
    en: 'MasterClass',
    categoryKey: 'education',
    contains: 'masterclass',
    priority: 285,
  },
  // — Travel: flights, hotels, car rental —
  {
    key: 'iberia',
    en: 'Iberia',
    categoryKey: 'travel',
    contains: 'iberia',
    priority: 290,
  },
  {
    key: 'ryanair',
    en: 'Ryanair',
    categoryKey: 'travel',
    contains: 'ryanair',
    priority: 291,
  },
  {
    key: 'vueling',
    en: 'Vueling',
    categoryKey: 'travel',
    contains: 'vueling',
    priority: 292,
  },
  {
    key: 'easyjet',
    en: 'EasyJet',
    categoryKey: 'travel',
    contains: 'easyjet',
    priority: 293,
  },
  {
    key: 'booking_com',
    en: 'Booking.com',
    categoryKey: 'travel',
    contains: 'booking.com',
    priority: 294,
  },
  {
    key: 'airbnb',
    en: 'Airbnb',
    categoryKey: 'travel',
    contains: 'airbnb',
    priority: 295,
  },
  {
    key: 'hostelworld',
    en: 'Hostelworld',
    categoryKey: 'travel',
    contains: 'hostelworld',
    priority: 296,
  },
  {
    key: 'expedia',
    en: 'Expedia',
    categoryKey: 'travel',
    contains: 'expedia',
    priority: 297,
  },
  {
    key: 'hertz',
    en: 'Hertz',
    categoryKey: 'travel',
    contains: 'hertz',
    priority: 298,
  },
  {
    key: 'avis',
    en: 'Avis',
    categoryKey: 'travel',
    contains: 'avis ',
    priority: 299,
  },
  {
    key: 'europcar',
    en: 'Europcar',
    categoryKey: 'travel',
    contains: 'europcar',
    priority: 300,
  },
  {
    key: 'sixt',
    en: 'Sixt',
    categoryKey: 'travel',
    contains: 'sixt',
    priority: 301,
  },
  {
    key: 'aeropuerto',
    en: 'Airport',
    categoryKey: 'travel',
    contains: 'aeropuerto',
    priority: 302,
  },
  {
    key: 'hotel',
    en: 'Hotel',
    categoryKey: 'travel',
    contains: 'hotel ',
    priority: 303,
  },
  // — Insurance, no dedicated category → other_expense —
  {
    key: 'mapfre',
    en: 'Mapfre',
    categoryKey: 'other_expense',
    contains: 'mapfre',
    priority: 310,
  },
  {
    key: 'axa',
    en: 'AXA',
    categoryKey: 'other_expense',
    contains: 'axa',
    priority: 311,
  },
  {
    key: 'linea_directa',
    en: 'Línea Directa',
    categoryKey: 'other_expense',
    contains: 'linea directa',
    priority: 312,
  },
  {
    key: 'mutua_madrilena',
    en: 'Mutua Madrileña',
    categoryKey: 'other_expense',
    contains: 'mutua madrilena',
    priority: 313,
  },
  {
    key: 'zurich_seguros',
    en: 'Zurich Seguros',
    categoryKey: 'other_expense',
    contains: 'zurich seguros',
    priority: 314,
  },
  {
    key: 'seguro_coche',
    en: 'Car insurance',
    categoryKey: 'other_expense',
    contains: 'seguro coche',
    priority: 315,
  },
  {
    key: 'seguro_hogar',
    en: 'Home insurance',
    categoryKey: 'other_expense',
    contains: 'seguro hogar',
    priority: 316,
  },
  // — Income: more salary terms —
  {
    key: 'sueldo',
    en: 'Salary (sueldo)',
    categoryKey: 'salary',
    contains: 'sueldo',
    priority: 320,
  },
  {
    key: 'salario',
    en: 'Salary',
    categoryKey: 'salary',
    contains: 'salario',
    priority: 321,
  },
  {
    key: 'paycheck',
    en: 'Paycheck',
    categoryKey: 'salary',
    contains: 'paycheck',
    priority: 322,
  },
  // — Income: gifts —
  {
    key: 'regalo',
    en: 'Gift (regalo)',
    categoryKey: 'gifts',
    contains: 'regalo',
    priority: 330,
  },
  {
    key: 'herencia',
    en: 'Inheritance',
    categoryKey: 'gifts',
    contains: 'herencia',
    priority: 331,
  },
  {
    key: 'donacion',
    en: 'Donation',
    categoryKey: 'gifts',
    contains: 'donacion',
    priority: 332,
  },
  // — Income: freelance, investment returns, refunds, transfers —
  {
    key: 'factura_emitida',
    en: 'Invoice issued',
    categoryKey: 'other_income',
    contains: 'factura emitida',
    priority: 340,
  },
  {
    key: 'freelance',
    en: 'Freelance',
    categoryKey: 'other_income',
    contains: 'freelance',
    priority: 341,
  },
  {
    key: 'dividendo',
    en: 'Dividend',
    categoryKey: 'other_income',
    contains: 'dividendo',
    priority: 342,
  },
  {
    key: 'dividend',
    en: 'Dividend',
    categoryKey: 'other_income',
    contains: 'dividend',
    priority: 343,
  },
  {
    key: 'devolucion',
    en: 'Refund (devolución)',
    categoryKey: 'other_income',
    contains: 'devolucion',
    priority: 344,
  },
  {
    key: 'reembolso',
    en: 'Reimbursement',
    categoryKey: 'other_income',
    contains: 'reembolso',
    priority: 345,
  },
  {
    key: 'cashback',
    en: 'Cashback',
    categoryKey: 'other_income',
    contains: 'cashback',
    priority: 346,
  },
  {
    key: 'bizum_recibido',
    en: 'Bizum received',
    categoryKey: 'other_income',
    contains: 'bizum recibido',
    priority: 347,
  },
  {
    key: 'subsidio',
    en: 'Subsidy',
    categoryKey: 'other_income',
    contains: 'subsidio',
    priority: 348,
  },
  // — Generic English keywords (parity with the Spanish generics above:
  //   supermercado/restaurante/salario…) so English-language statements
  //   categorize too —
  {
    key: 'salary',
    en: 'Salary (salary)',
    categoryKey: 'salary',
    contains: 'salary',
    priority: 350,
  },
  {
    key: 'supermarket',
    en: 'Supermarket (EN)',
    categoryKey: 'groceries',
    contains: 'supermarket',
    priority: 351,
  },
  {
    key: 'grocery',
    en: 'Grocery',
    categoryKey: 'groceries',
    contains: 'grocery',
    priority: 352,
  },
  {
    key: 'coffee',
    en: 'Coffee shop',
    categoryKey: 'restaurants',
    contains: 'coffee',
    priority: 353,
  },
  {
    key: 'restaurant',
    en: 'Restaurant (EN)',
    categoryKey: 'restaurants',
    contains: 'restaurant',
    priority: 354,
  },
  {
    key: 'gym',
    en: 'Gym (EN)',
    categoryKey: 'health',
    contains: 'gym',
    priority: 355,
  },
  {
    key: 'electricity',
    en: 'Electricity (EN)',
    categoryKey: 'utilities',
    contains: 'electricity',
    priority: 356,
  },
] as const
